project_id = ""

[functions.register]
verify_jwt = false

[functions.recover]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.storage-sweep]
verify_jwt = true

[functions.account-email]
verify_jwt = false

[functions.change-password]
verify_jwt = true
