"""Conservative provisional difficulty assignment for newly imported sentences.
Existing card levels always take precedence. Labels remain Level 1..6, not CEFR claims.
"""
import re
BASIC=set('minä sinä hän me te he se tämä tuo nämä nuo olen olet on olemme olette ovat ole en et ei emme ette eivät kuka mikä mitä missä miten kuinka milloin miksi kyllä ei kiitos anteeksi hei moi hyvää hyvä päivää huomenta iltaa yötä huomiseen näkemiin tervetuloa poika tyttö lapsi lapset mies nainen äiti isä veli sisko koira kissa koti koulu kirja kahvi tee vesi maito ruoka leipä kala liha iso pieni uusi vanha kylmä kuuma lämmin kaunis pitkä lyhyt tyhjä täysi auki kiinni valmis täällä siellä tässä tuolla nyt tänään huomenna eilen aina usein joskus vielä jo pian hyvin huonosti paljon vähän liian todella ja tai mutta myös vain kaikki yksi kaksi kolme neljä viisi kuusi seitsemän kahdeksan yhdeksän kymmenen sata tuhat nälkä jano opiskelija opiskelijat opettaja lääkäri suomalainen suomi suomea englanti englantia ranska ranskaa ruotsi ruotsia iloinen onnellinen surullinen vihainen terve sairas väsynyt naimisissa oikeassa väärässä yksin yhdessä töissä kotona sisään ulos alas ylös tänne sinne totta hauskaa anteeksi rahaa aikaa minulla sinulla hänellä meillä teillä heillä minun sinun hänen meidän teidän heidän minua sinua häntä meitä teitä heitä minulle sinulle hänelle meille teille heille minun sinun sen sitä tätä tuota tomi tom tomin mari marin mary maryn'.split())
EVERYDAY=('syö','juo','nuku','nukk','mene','menn','tule','tull','asu','asuu','istu','seiso','käve','puhu','sano','sanoo','kysy','vastaa','lue','luke','kirjo','osta','myy','avaa','sulje','katso','kuule','kuunte','näe','näke','nähdä','halua','tarvit','osaa','opiskel','rakasta','pidä','pitä','tykkää','etsi','löydä','odota','odotta','anna','anta','ota','otta','laita','pese','pesi','autta','auta','tanssi','laula','ui','uida','pelaa','pelata','matkusta','soita','soitta','tiedä','tietä','tunne','tunte','muista','unoh','yritä','yrittä','voi','voiko','voin','vois','käy','käydä','laps','kaup','perhe','ystäv','kaver','koul','kirj','auto','buss','juna','talo','huone','ovi','ikkuna','pöy','sän','seng','vuode','keitti','ruo','ruua','leip','kahv','mai','vesi','vede','viini','olut','olue','työ','töi','päiv','viik','kuukau','vuos','vuod','aamu','ilta','yö','kesä','talv','kevä','syks','tunti','minuut','kello','sää','sata','satoi','aurin','sade','lumi','lunta','raha','euro','hinta','maks','lip','lääkä','saira','apteek','jalka','käsi','kättä','pää','silmä','korva','nenä','suu','hamma','vaate','ken','tak','paita','puhe','känny','puhel','tietoko','net','kaupun','maa','suom','ransk','espan','engl','boston','helsin','ruots','omena','banaani','muna','salaat','juust','suklaa','liha','kala','maista','herää','herä','kuole','kuoli','naura','nauro','itke','itki','pelkää','pelkä','pelkäs','oppi','oppii','lähti','lähde','lähte','jää','jäädä','joi','söi','söin','join','oli','olit','olin','olimme','olivat','meni','menit','menin','tuli','tulin','tulit','näin','näit','näki','tein','teit','teki','sai','sain','sait','sanoit','kertoi','kerro','luin','luit','luki','piti','pidin','pesin','pesit','tiesi','tunsi','tunsin','jotain','jotakin','mitään','kukaan','kukaan','kerran','koskaan','taas','uudest','sitten','ennen','jälkeen','kansa','kanssa','mukaan','ilman','asti','lähel','kaukana')
PAST=re.compile(r'\b(?:olin|olit|oli|olimme|olitte|olivat|menin|menit|meni|tulin|tulit|tuli|söin|söit|söi|join|joit|joi|näin|näit|näki|tein|teit|teki|sain|sait|sai|luin|luit|luki|puhuin|puhuit|puhui|ostin|ostit|osti|halusin|halusit|halusi|tiesin|tiesit|tiesi|löysin|löysit|löysi|en\s+\w+(?:nut|nyt|lut|lyt|sut|syt|rut|ryt))\b')
CLAUSES={'että','jos','koska','vaikka','kun','joka','jossa','johon','josta','jotta','ellei','mikäli','kunnes'}
COLLOQ={'mä','sä','mää','sää','mun','sun','mua','sua','oon','oot','oo','et','ku','musta','susta','tää','toi','täs','siel','täälläpäin','itte','itteäni','itteensä','kyl','tiiä','tiä','mut','ootko','mullon','mulla','sulla','mul','sul','meiän','teilläpäin','emmä','sun','mun','kaa','oots','mäki'}
def assign(text):
 w=re.findall(r"[a-zåäö]+",text.lower());n=len(w)
 known=lambda t:t in BASIC or t.startswith(EVERYDAY) or t.endswith('ko') and t[:-2] in BASIC or t.endswith('kö') and t[:-2] in BASIC
 unknown=[t for t in w if not known(t)]
 reasons=[];score=2
 if n<=5 and all(t in BASIC or t in {'haluan','haluat','haluaa','syön','syöt','syö','juon','juot','juo','asun','asut','asuu','puhun','puhut','puhuu','kiitos','anteeksi','onko','olenko','oletko','ovatko'} for t in w):score=1;reasons.append('Grundwortschatz und kurze Struktur')
 elif not unknown and n<=7:score=2;reasons.append('Alltagssatz mit einfacher Struktur')
 else:score=3;reasons.append('Erweiterter Wortschatz')
 if len(unknown)>=2:score=max(score,4)
 if len(unknown)>=3 and len(unknown)/max(n,1)>.45:score=max(score,5);reasons.append('Mehrere weniger geläufige Wörter')
 if any(len(t)>=15 for t in unknown):score=max(score,5);reasons.append('Langes oder zusammengesetztes Wort')
 if PAST.search(text.lower()):score=max(score,3);reasons.append('Vergangenheit')
 if re.search(r'\b(?:en|et|ei|emme|ette|eivät)?\s*(?:ole|olen|olet|on|olemme|olette|ovat)\b.{0,35}\b\w+(?:nut|nyt|neet|lut|lyt|leet|ttu|tty|ttuja|tyt)\b',text.lower()):score=max(score,4);reasons.append('Zusammengesetzte Verbform')
 if any(re.search(r'isi(?:n|t|mme|tte|vat|vät|ko|kö|tko|tkö)?$',t) for t in w if t not in {'viisi','kuusi'}):score=max(score,4);reasons.append('Möglicher Konditional')
 if CLAUSES.intersection(w):score=max(score,4);reasons.append('Nebensatz oder Bedingung')
 if len(CLAUSES.intersection(w))>1 or n>=10:score=max(score,6);reasons.append('Mehrteilige Satzstruktur')
 if COLLOQ.intersection(w)-{'et','musta'} or any(t.endswith(('ksä','ksme','taaks','tetaaks','ksme')) for t in w):score=max(score,5);reasons.append('Umgangssprachliche Form')
 if any(t in {'ärsyttääkseen','puhuakseen','kuunnellessani','pysyäkseen','pelastaakseen','tehneensä','valehdelleensa','auttavasi','jättävänsä','kunnioittavan','aukeavan','kehittyväni','tietävän','kärsivän'} for t in w):score=max(score,6);reasons.append('Verdichtete Verbkonstruktion')
 if n>=10 and len(unknown)>=4:score=6;reasons.append('Komplexer Satz und erweiterter Wortschatz')
 # Past forms in the existing, manually selected grammar dictionary.
 from build_grammar import rules
 if any(title=='Einfache Vergangenheit (Imperfekti)' and re.search(r'(?<!\w)'+re.escape(form)+r'(?!\w)',text,re.I) for form,title,_,_ in rules):score=max(score,3);reasons.append('Vergangenheitsform')
 if re.search(r'\b\w+(?:imme|itte|ivat|ivät)\b',text.lower()):score=max(score,3);reasons.append('Mögliche Vergangenheit im Plural')
 return score,{'status':'estimated','method':'grammar-vocabulary-v1','reasons':reasons}
